version: "3.8"
services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - broker

  broker:
    image: rabbitmq:3.9
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: celery -A main_app.celery worker --loglevel=info
    depends_on:
      - django
      - broker

volumes:
  rabbitmq-data:
